version: '2'

services:
  grades_email_sender:
    image: 'grades_email_sender:1.0'
    build:
      context: .
    container_name: grades_email_sender
    ports:
      - '8080:8080'
    depends_on:
      - grades_email_sender_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://grades_email_sender_db:5432/grades
      - SPRING_DATASOURCE_USERNAME=grades_email_sender
      - SPRING_DATASOURCE_PASSWORD=#EmailNotas10
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  grades_email_sender_db:
    image: 'postgres:14.3'
    container_name: grades_email_sender_db
    volumes:
      - /database/grades:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=grades_email_sender
      - POSTGRES_PASSWORD=#EmailNotas10